local actions = require "telescope.actions"

require("telescope").setup {
  pickers = {
    keymaps = {
      layout_config = { width = 0.55, height = 0.55 },
      lhs_filter = function(lhs)
        -- get rid of the Þ character generated by which-key
        if string.find(lhs, "Þ") then
          return false
        end
        return true
      end,
    },
  },
  extensions = {
    fzf = {
      fuzzy = true,
      override_generic_sorter = true,
      override_file_sorter = true,
      case_mode = "smart_case",
    },
    persisted = {
      layout_config = { width = 0.55, height = 0.55 },
    },
  },
  defaults = {
    vimgrep_arguments = {
      "rg",
      "-L",
      "--color=never",
      "--no-heading",
      "--with-filename",
      "--line-number",
      "--column",
      "--smart-case",
      "--trim",
    },
    dynamic_preview_title = true, -- neoclip 使用这个更改标题
    prompt_prefix = "   ",
    selection_caret = "  ",
    entry_prefix = "  ",
    initial_mode = "insert",
    selection_strategy = "reset",
    sorting_strategy = "ascending",
    layout_strategy = "horizontal",
    layout_config = {
      horizontal = {
        prompt_position = "top",
        preview_width = 0.55,
        results_width = 0.8,
      },
      vertical = {
        mirror = false,
      },
      width = 0.70,
      height = 0.80,
      preview_cutoff = 120,
    },
    file_sorter = require("telescope.sorters").get_fuzzy_file,
    file_ignore_patterns = { "node_modules" },
    generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter,
    path_display = { "truncate" },
    winblend = 0,
    border = {},
    borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
    color_devicons = true,
    set_env = { ["COLORTERM"] = "truecolor" }, -- default = nil,
    file_previewer = require("telescope.previewers").vim_buffer_cat.new,
    grep_previewer = require("telescope.previewers").vim_buffer_vimgrep.new,
    qflist_previewer = require("telescope.previewers").vim_buffer_qflist.new,
    buffer_previewer_maker = require("telescope.previewers").buffer_previewer_maker,
    mappings = {
      n = { ["q"] = actions.close },
      i = {
        ["<C-u>"] = false,
        ["<C-d>"] = actions.delete_buffer + actions.move_to_top,
      },
    },
  },
}

local extensions = {
  "fzf",
  "projects",
  "yank_history",
  "dap",
  "aerial",
  "persisted",
  "undo",
}

for _, ext in ipairs(extensions) do
  require("telescope").load_extension(ext)
end
